[package]
name = "payments_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
num_cpus = "1.17.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[dev-dependencies]
tempfile = "3.24"
